### ISSUE TITLE
Architecture: What is the difference between single image and batch?

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/animl-ingest#38]
... Couldn't the single image be processes as a batch of one?

**Comment by nathanielrindlaub** [comment]
The input for batch will be a zipped up folder of individual images. Does that help?

**Comment by postfalk** [comment]
So is the zip workflow:
- call unzip 
- which creates new objects which trigger animl-ingest again?

**Comment by nathanielrindlaub** [comment]
This is @ingalls code so he can speak to it and the bulk-upload plan w/ more specificity, but right now I believe it is not wired up to the rest of the data ingestion pipeline. It's just the first step of the bulk upload workflow; building out the rest is part of the next SOW (I will email you that doc in one sec). 

Ultimately the `ingest-zip` handler will start an AWS Batch job that unzip the folder and does a few additional things that are not required in the normal image ingestion process, including spin up unique SQS queues for each job so that users can track their upload and inference progress and write corresponding records for storing progress updates to the DB, etc.

We can discuss this in more detail when @ingalls is ready to get started on this next SOW - I think we're shooting to get started the week of the 30th or the following week.

**Comment by postfalk** [comment]
I wonder if we could provide a different bucket for this. It would separate concerns much better. And then the other process would do its thing and then store images in the standard bucket. OR we would put parts of the codes i.e. process_image into a layer and use in different lambdas but in this case it needs to be done in Python or Node but not in both.
